### ISSUE TITLE
EventType Weights

### ISSUE THREAD

**Issue by Qugar** [Sylkadi/BrutalCompanyMinus#2]
Hi,

Maybe I'm stupid but somehow I think the EventType Weights don't work properly. Of course, it's also possible that I didn't fully understand how weighted chance works.

Regarding my exact problem. I tried to set up the frequency of the events for a long time, based on what I understood to be weighted chance, but even after hundreds of tests the results seemed strange to me.

I then set all EventType Weights to 1. If I understand correctly, in this case each category should have a 16.67% chance of being selected. These are the results after 200 runs.

![grafik](https://github.com/Sylkadi/BrutalCompanyMinus/assets/8191849/68024102-d0d2-48fe-802f-f8e7f6bb993e)

Am I correct that these results are very unlikely and something is going wrong or have I not understood weighted chance?

Sorry for my English, it's not my native language.

**Comment by Sylkadi** [comment]
These results seem correct except the neutral one. And you have understood what it is.
But the actual probabilities will be more complicated than that because some events will remove other events from happening or some events have conditions to be activated.
![Screenshot_117](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/61a848b7-e205-452d-bf67-0afc2255f987).
And in general there are some very bad events that will remove the lesser version of it so having everything set to 1, very bad should happen more commonly than bad.
![Screenshot_118](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/d806f291-5325-4ac0-90c6-bc57e75c1f47)
These results should also vary depending on the amount of events chosen.

When i get home from work i'll test this myself.

**Comment by Qugar** [comment]
I should probably mention that I changed the number of events per round to one. The costum weights are set to false so that the mod should use the eventType weights and I disabled some events but every event type is represented at least once.

**Comment by Sylkadi** [comment]
What events did you disable?

Edit: I see the problem

**Comment by Qugar** [comment]
Neutral - Birds, LeaflessBrownTrees, LeaflessTrees ,Locusts, Trees
Bad - Bees, DoorGlitch, OutsideLandmines, OutsideTurrets
Very Bad - ForestGiant, InsideBees, Warzone

**Comment by Sylkadi** [comment]
Simple fix but i will release whenever I decide to make some new events, and out of my own curiosity I tallied the events 1,000,000 times for 1, 3, 8 and 20 Events all on experimentation using default weights.

**1 Events**
![1Event](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/e1f290da-874b-4a1f-a03f-632b99d83db2)

**3 Events**
![3Events](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/d18ff1ef-4655-46f6-86b2-325466fff78d)

**8 Events**
![8Events](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/2b289357-9bfa-407f-ad60-5fd834f3dc5e)

**20 Events**
![20Events](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/d5eca5ca-c966-44c1-a75d-5b0b61fa0f83)

**Comment by Qugar** [comment]
That looks really good, thank you.
Great work and really great mod.
